version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "5000:5000"
    networks:
      - hotel-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "8080:8080"
    depends_on:
      api:
        condition: service_started # wait for API to be started
    environment:
      - API_URL=http://api:5000/api
      - DB_HOST=host.docker.internal
      - DB_PORT=3306
      - DB_USER=webapp_user
      - DB_PASSWORD=Admin123!
      - DB_NAME=fonteyn_database
    networks:
      - hotel-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  hotel-network:  #it is a custom bridge network to allow communication between containers
    driver: bridge